# Generated by Django 3.0.10 on 2020-09-10 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_goal_pain_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='color',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
