# Generated by Django 3.0.10 on 2020-09-12 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0004_auto_20200912_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='color',
            field=models.CharField(choices=[('#C21807', 'Chili'), ('#E0115F', 'Ruby'), ('#C64B8C', 'Mulberry'), ('#B66OCD', 'Lilac'), ('#EC5578', 'PUNCH'), ('#F64A8A', 'French Rose'), ('#81007F', 'Lollipop'), ('#8D4585', 'Plum'), ('#F987C5', 'Taffy'), ('#FD6A02', 'Tiger'), ('#FCE205', 'Bumblelee'), ('#EB9605', 'Honey'), ('#EFFD5F', 'Lemon'), ('#98FB98', 'Mint'), ('#98FB98', 'Mint'), ('#2E8B57', 'Sea'), ('#4F7942', 'Fern'), ('#29AB87', 'Jungle'), ('#808588', 'Lava'), ('#4682B4', 'Steel'), ('#0080FE', 'Azure'), ('#57A0D2', 'Carolina'), ('#1C2951', 'Space'), ('#4B3619', 'Coffee'), ('#4B382A', 'Espresso')], default='#EB9605', max_length=7),
        ),
    ]
