# Generated by Django 3.0.10 on 2020-09-12 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0005_auto_20200912_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='is_completed',
            field=models.BooleanField(blank=True),
        ),
    ]
