# Generated by Django 3.0.10 on 2020-09-16 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0010_auto_20200915_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='is_completed',
            field=models.BooleanField(blank=True, default=False, verbose_name='Did you complete it?'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='measurable_context',
            field=models.TextField(blank=True, help_text='What was a highlight today? Was there anything challenging? What are you looking forward to? What needs growth and nurturing?', null=True, verbose_name='Anything else you want to reflect on?'),
        ),
    ]
