# Generated by Django 3.0.10 on 2020-09-16 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0011_auto_20200916_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='name',
            field=models.CharField(help_text='If your goal is to get in shape, your system is to eat healthy everyday and exercise 3 times a week. If your goal is to write a 300-page book by the end of this month, your system is to write 10 pages a day.', max_length=200, verbose_name='What is your system?'),
        ),
    ]
